baseURL = "https://skardian.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Skardian.io"
theme = ["hugo-redirect","uBlogger"]
enableEmoji = true


[params]
  # uBlogger theme version
  version = "1.3.X"
[params.home]
  [params.home.profile]
    enable = true
    gravatarEmail = "jose.carlos.padial@gmail.com"
    title = "Skardian | Hago cosas"
    subtitle = "¡Holabuenas! Esto no es un blog de tecnología, es un espacio para hablar de mis cosas."
    social = true

[params.social]
  Twitter = "skardian"
  Instagram = "skardian"
  Twitch = "skardian"
  GitHub = "skardian"
  RSS = true

[params.footer]
  hugo = false
  author = true
    # Site creation time
  since = 2021
  copyright = true
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.page]
  theme = "full"
  [params.page.toc]
    enable = false

[params.search]
  enable = true
  type = "lunr"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"


[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]