baseURL: 'https://skardian.io/'
defaultContentLanguage: en
languageCode: en
title: Skardian.io
theme:
  - hugo-redirect
  - uBlogger
enableEmoji: true
params:
  version: 1.3.X
  home:
    profile:
      enable: true
      gravatarEmail: jose.carlos.padial@gmail.com
      title: Skardian | Hago cosas
      subtitle: >-
        ¡Holabuenas! Esto no es un blog de tecnología, es un espacio para hablar
        de mis cosas.
      social: true
  social:
    Twitter: skardian
    Instagram: skardian
    Twitch: skardian
    GitHub: skardian
    RSS: true
  footer:
    hugo: true
    author: true
    since: 2020
    copyright: true
    license: >-
      <a rel="license external nofollow noopener noreffer"
      href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC
      BY-NC 4.0</a>
  page:
    theme: full
    toc:
      enable: false
  search:
    enable: true
    type: lunr
    contentLength: 4000
    placeholder: ''
    maxResultLength: 10
    snippetLength: 30
    highlightTag: em
menu:
  main:
    - identifier: blog
      name: Blog
      url: /posts/
      title: ''
      weight: 1
    - identifier: about
      pre: ''
      post: ''
      name: About
      url: /about/index.html
      title: ''
      weight: 2
    - identifier: tags
      pre: ''
      post: ''
      name: Tags
      url: /tags/
      title: ''
      weight: 3
markup:
  highlight:
    noClasses: false
  goldmark: {}
renderer:
  unsafe: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
